Fixing scanner to use correct analysis id and wait for analysis to be complete before returning project status.

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -33,13 +33,35 @@ if [ -z "${analysis_id}" ]; then
   exit 1
 fi
 
+# wait for analysis to be complete
+ce_task_info="./ce_task.json"
+ce_task_status="PENDING"
+until [ "${ce_task_status}" != "PENDING" ] && [ "${ce_task_status}" != "IN_PROGRESS" ]; do
+  curl -s -u "${sonar_login}:" -L -o "${ce_task_info}" "${sonar_host_url}/api/ce/task?id=${analysis_id}"
+  ce_task_status=$(jq -r '.task.status // ""' < "${ce_task_info}")
+  if [ "${ce_task_status}" == "PENDING" ] || [ "${ce_task_status}" == "IN_PROGRESS" ]; then
+    echo "Waiting for compute engine result (sleep: 5s)..."
+    sleep 5 # Poll SonarQube compute engine task every 5 seconds.
+  fi
+done
+
+analysis_id=""
+if [ "${ce_task_status}" == "SUCCESS" ]; then
+  analysis_id=$(jq -r '.task.analysisId // ""' < "${ce_task_info}")
+  if [ -z "${analysis_id}" ]; then
+    echo "error: No analysis ID could be fetched from compute engine task result"
+    exit 1
+  fi
+fi
+
 curl -s -u "${sonar_login}:" -L -o sonar-qualitygates-status.json "${sonar_host_url}/api/qualitygates/project_status?analysisId=${analysis_id}"
 
-qualitygates_status=$(jq -r '.projectStatus.status' < "sonar-qualitygates-status.json")
+project_status=$(jq -r '.projectStatus.status' < "sonar-qualitygates-status.json")
 
 jq -n "{
   version: { \"analysis_id\": \"${analysis_id}\" },
   metadata: [
-    { name: \"qualitygates_status\", value: \"${qualitygates_status:?}\" }
+    { name: \"ce_task_status\", value: \"${ce_task_status}\" },
+    { name: \"project_status\", value: \"${project_status:?}\" }
   ]
 }" >&3
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -51,7 +51,7 @@ if [ -z "${source}" ]; then
   exit 1
 fi
 
-cd $source
+cd "$source"
 
 projects=$(jq -r '.params.projects // ""' < "${payload}")
 if [ -z "${projects}" ]; then
@@ -59,7 +59,7 @@ if [ -z "${projects}" ]; then
 fi
 
 options=""
-extraParams=$(jq -r '.params.extra_params[] // ""' < "${payload}")
+extraParams=$(jq -r 'if .params.extra_params then .params.extra_params[] else empty end' < "${payload}")
 for ep in $extraParams; do options+="/d:$ep "; done
 
 mono /opt/sonar-scanner-msbuild/SonarQube.Scanner.MSBuild.exe begin /d:sonar.host.url=$sonar_host_url /d:sonar.login=$sonar_login /k:$sonar_project_key /n:"$sonar_project_name" /v:$version_val $options
@@ -67,11 +67,23 @@ for p in $projects; do dotnet restore $p; done
 for p in $projects; do dotnet build $p; done
 mono /opt/sonar-scanner-msbuild/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=$sonar_login
 
-analysis_id=$(curl -u "${sonar_login}:" -s -L "${sonar_host_url}/api/ce/activity?q=${sonar_project_key}&onlyCurrents=true" | jq -r .tasks[0].analysisId)
+scanner_report_file=.sonarqube/out/.sonar/report-task.txt
+
+echo "Reading SonarQube scanner report (${scanner_report_file})..."
+if [ -f "${scanner_report_file}" ]; then
+  while read -r line; do declare $line; done < ${scanner_report_file}
+else
+  echo "error: SonarQube report could not be located."
+  exit 1
+fi
 
 jq -n "{
-  version: { \"analysis_id\": \"${analysis_id}\" },
+  version: {analysis_id: \"${ceTaskId:?}\"},
   metadata: [
-    { name: \"project_key\", value: \"${sonar_project_key:?}\" }
+    { name: \"project_key\", value: \"${projectKey:?}\" },
+    { name: \"server_url\", value: \"${serverUrl:?}\" },
+    { name: \"server_version\", value: \"${serverVersion:?}\" },
+    { name: \"dashboard_url\", value: \"${dashboardUrl:?}\" },
+    { name: \"ce_task_url\", value: \"${ceTaskUrl:?}\" }
   ]
 }" >&3
